##################### CrateDB Configuration ########################
#
# Notes: https://crate.io/docs/reference/en/2.2.0/configuration.html
#
####################################################################

license.enterprise: {{cfg.license.enterprise}}

{{#if cfg.cluster.name}}
  cluster.name: {{cfg.cluster.name}}
{{/if}}

{{#if svc.me.leader ~}}
  node.master: true
{{else ~}}
  node.master: false
{{/if ~}}

discovery.zen.ping.unicast.hosts:

{{#each svc.members ~}}
  - {{sys.ip}}:{{cfg.port.transport}}
{{/each}}

path.data: {{pkg.svc_var_path}}/data
path.logs: {{pkg.svc_var_path}}/logs
blobs.path: {{pkg.svc_var_path}}/data/blobs
